// <auto-generated />
using System;
using Examen.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Examen.Infrastructure.Migrations
{
    [DbContext(typeof(ExamenDbContext))]
    [Migration("20260610115722_Addemailnotific")]
    partial class Addemailnotific
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Alerte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeArticle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeMachine")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CommentaireResolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAlerte")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateResolution")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LotId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NbNonConformesConsecutifs")
                        .HasColumnType("int");

                    b.Property<int>("Niveau")
                        .HasColumnType("int");

                    b.Property<string>("NumOF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantiteDefauts")
                        .HasColumnType("int");

                    b.Property<int>("QuantiteTotale")
                        .HasColumnType("int");

                    b.Property<int?>("ResolueParId")
                        .HasColumnType("int");

                    b.Property<int?>("SeuilId")
                        .HasColumnType("int");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<decimal>("TauxDetecte")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CodeMachine");

                    b.HasIndex("DateAlerte");

                    b.HasIndex("LotId");

                    b.HasIndex("ResolueParId");

                    b.HasIndex("SeuilId");

                    b.HasIndex("Statut");

                    b.ToTable("Alertes");
                });

            modelBuilder.Entity("CommentaireAlerte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlerteId")
                        .HasColumnType("int");

                    b.Property<int>("AuteurId")
                        .HasColumnType("int");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomAuteur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AlerteId");

                    b.ToTable("CommentairesAlerte", (string)null);
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.DestinataireNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Canal")
                        .HasColumnType("tinyint");

                    b.Property<string>("Destinataire")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<byte>("NiveauMinimum")
                        .HasColumnType("tinyint");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("DestinatairesNotification", (string)null);
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.HistoriqueNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlerteId")
                        .HasColumnType("int");

                    b.Property<byte>("Canal")
                        .HasColumnType("tinyint");

                    b.Property<string>("Corps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateEnvoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLecture")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destinataire")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ErreurMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NbTentatives")
                        .HasColumnType("int");

                    b.Property<byte>("Statut")
                        .HasColumnType("tinyint");

                    b.Property<string>("Sujet")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlerteId");

                    b.HasIndex("Statut");

                    b.ToTable("HistoriqueNotifications", (string)null);
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.PredictionDefaut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePrediction")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstDefectueux")
                        .HasColumnType("bit");

                    b.Property<string>("FeaturesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LatenceMs")
                        .HasColumnType("int");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NiveauRisque")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Probabilite")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("ResultatControleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShapExplicationJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypeDefautPreditId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeDefautPreditId");

                    b.ToTable("PredictionsDefauts");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Produit", b =>
                {
                    b.Property<string>("CodeArticle")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Cadence")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomProduit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TailleEchantillonnage")
                        .HasColumnType("int");

                    b.HasKey("CodeArticle");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.ResultatControle", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("Cadence")
                        .HasColumnType("int");

                    b.Property<string>("CodeArticle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CodeArticle");

                    b.Property<string>("CodeMachine")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DateControle")
                        .HasColumnType("datetime2");

                    b.Property<string>("Defaut1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Defaut2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("LotId")
                        .HasColumnType("int");

                    b.Property<int>("NbDefautsTest1")
                        .HasColumnType("int");

                    b.Property<int>("NbDefautsTest2")
                        .HasColumnType("int");

                    b.Property<int>("NbEchantillons")
                        .HasColumnType("int");

                    b.Property<string>("NumOF")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProduitCodeArticle")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<string>("SolutionGlobale")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StatutLot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TypeDefaut1Id")
                        .HasColumnType("int");

                    b.Property<int?>("TypeDefaut2Id")
                        .HasColumnType("int");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodeMachine");

                    b.HasIndex("LotId");

                    b.HasIndex("ProduitCodeArticle");

                    b.HasIndex("TypeDefaut1Id");

                    b.HasIndex("TypeDefaut2Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("ResultatControles");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Seuil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeArticle")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodeMachine")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("CreePar")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<decimal>("SeuilPourcentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("TypeDefaut1Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodeArticle");

                    b.HasIndex("CodeMachine");

                    b.HasIndex("TypeDefaut1Id");

                    b.ToTable("Seuils", (string)null);
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.TypeDefaut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CauseProbable")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Frequence")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomDefaut")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("TypeDefauts");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Lot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NumeroLot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OperateurId")
                        .HasColumnType("int");

                    b.Property<string>("ProduitId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("QuantitePrevue")
                        .HasColumnType("int");

                    b.Property<int?>("QuantiteProduite")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("OperateurId");

                    b.HasIndex("ProduitId");

                    b.ToTable("Lot");
                });

            modelBuilder.Entity("Machine", b =>
                {
                    b.Property<string>("CodeMachine")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("NomMachine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CodeMachine");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("Alerte", b =>
                {
                    b.HasOne("Lot", null)
                        .WithMany("Alertes")
                        .HasForeignKey("LotId");

                    b.HasOne("Examen.ApplicationCore.Domain.Utilisateur", "ResoluePar")
                        .WithMany()
                        .HasForeignKey("ResolueParId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Examen.ApplicationCore.Domain.Seuil", "Seuil")
                        .WithMany("Alertes")
                        .HasForeignKey("SeuilId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ResoluePar");

                    b.Navigation("Seuil");
                });

            modelBuilder.Entity("CommentaireAlerte", b =>
                {
                    b.HasOne("Alerte", "Alerte")
                        .WithMany("Commentaires")
                        .HasForeignKey("AlerteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alerte");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.DestinataireNotification", b =>
                {
                    b.HasOne("Examen.ApplicationCore.Domain.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.HistoriqueNotification", b =>
                {
                    b.HasOne("Alerte", "Alerte")
                        .WithMany("Notifications")
                        .HasForeignKey("AlerteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alerte");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.PredictionDefaut", b =>
                {
                    b.HasOne("Examen.ApplicationCore.Domain.TypeDefaut", "TypeDefautPredit")
                        .WithMany()
                        .HasForeignKey("TypeDefautPreditId");

                    b.Navigation("TypeDefautPredit");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.ResultatControle", b =>
                {
                    b.HasOne("Machine", "Machine")
                        .WithMany("ResultatControles")
                        .HasForeignKey("CodeMachine")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lot", null)
                        .WithMany("ResultatsControle")
                        .HasForeignKey("LotId");

                    b.HasOne("Examen.ApplicationCore.Domain.Produit", null)
                        .WithMany("ResultatControles")
                        .HasForeignKey("ProduitCodeArticle");

                    b.HasOne("Examen.ApplicationCore.Domain.TypeDefaut", "TypeDefaut1")
                        .WithMany()
                        .HasForeignKey("TypeDefaut1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Examen.ApplicationCore.Domain.TypeDefaut", "TypeDefaut2")
                        .WithMany()
                        .HasForeignKey("TypeDefaut2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Examen.ApplicationCore.Domain.Utilisateur", "Utilisateur")
                        .WithMany("ResultatControles")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("TypeDefaut1");

                    b.Navigation("TypeDefaut2");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Seuil", b =>
                {
                    b.HasOne("Examen.ApplicationCore.Domain.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("CodeArticle")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("CodeMachine")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Examen.ApplicationCore.Domain.TypeDefaut", "TypeDefaut1")
                        .WithMany()
                        .HasForeignKey("TypeDefaut1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Machine");

                    b.Navigation("Produit");

                    b.Navigation("TypeDefaut1");
                });

            modelBuilder.Entity("Lot", b =>
                {
                    b.HasOne("Machine", "Machine")
                        .WithMany("Lots")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Examen.ApplicationCore.Domain.Utilisateur", "Operateur")
                        .WithMany("Lots")
                        .HasForeignKey("OperateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Examen.ApplicationCore.Domain.Produit", "Produit")
                        .WithMany("Lots")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Operateur");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("Alerte", b =>
                {
                    b.Navigation("Commentaires");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Produit", b =>
                {
                    b.Navigation("Lots");

                    b.Navigation("ResultatControles");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Seuil", b =>
                {
                    b.Navigation("Alertes");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Utilisateur", b =>
                {
                    b.Navigation("Lots");

                    b.Navigation("ResultatControles");
                });

            modelBuilder.Entity("Lot", b =>
                {
                    b.Navigation("Alertes");

                    b.Navigation("ResultatsControle");
                });

            modelBuilder.Entity("Machine", b =>
                {
                    b.Navigation("Lots");

                    b.Navigation("ResultatControles");
                });
#pragma warning restore 612, 618
        }
    }
}
