// <auto-generated />
using System;
using Examen.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Examen.Infrastructure.Migrations
{
    [DbContext(typeof(ExamenDbContext))]
    [Migration("20260402132321_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Machine", b =>
                {
                    b.Property<string>("CodeMachine")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("NomMachine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CodeMachine");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Produit", b =>
                {
                    b.Property<string>("CodeArticle")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomProduit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TailleEchantillonnage")
                        .HasColumnType("int");

                    b.HasKey("CodeArticle");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.ResultatControle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Cadence")
                        .HasColumnType("int");

                    b.Property<string>("CodeArticle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeMachine")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DateControle")
                        .HasColumnType("datetime2");

                    b.Property<string>("Defaut1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Defaut2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineCodeMachine")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NbDefautsTest1")
                        .HasColumnType("int");

                    b.Property<int>("NbDefautsTest2")
                        .HasColumnType("int");

                    b.Property<int>("NbEchantillons")
                        .HasColumnType("int");

                    b.Property<string>("NumOF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<string>("SolutionGlobale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatutLot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.Property<int?>("UtilisateurId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodeMachine");

                    b.HasIndex("MachineCodeMachine");

                    b.HasIndex("UtilisateurId");

                    b.HasIndex("UtilisateurId1");

                    b.ToTable("ResultatControles");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.TypeDefaut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeArticle")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Frequence")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomDefaut")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CodeArticle");

                    b.ToTable("TypeDefauts");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.ResultatControle", b =>
                {
                    b.HasOne("Examen.ApplicationCore.Domain.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("CodeMachine")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("Examen.ApplicationCore.Domain.Machine", null)
                        .WithMany("ResultatControles")
                        .HasForeignKey("MachineCodeMachine");

                    b.HasOne("Examen.ApplicationCore.Domain.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("Examen.ApplicationCore.Domain.Utilisateur", null)
                        .WithMany("ResultatControles")
                        .HasForeignKey("UtilisateurId1");

                    b.Navigation("Machine");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.TypeDefaut", b =>
                {
                    b.HasOne("Examen.ApplicationCore.Domain.Produit", "Produit")
                        .WithMany("TypeDefauts")
                        .HasForeignKey("CodeArticle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Machine", b =>
                {
                    b.Navigation("ResultatControles");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Produit", b =>
                {
                    b.Navigation("TypeDefauts");
                });

            modelBuilder.Entity("Examen.ApplicationCore.Domain.Utilisateur", b =>
                {
                    b.Navigation("ResultatControles");
                });
#pragma warning restore 612, 618
        }
    }
}
